version: '3.1'

services:
  app:
    build: .
    ports:
      - "3000:3000"
  database:
    image: postgres
    environment:
      POSTGRES_USER: kyhan
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: transcendence
    ports:
      - "5432:5432"
